name: weird.agency
favicon: null
layout_spectrum: 0.22659
typography_spectrum: 0.62959
title: Welcome to Weird.Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefaf7'
    - '#3d3332'
    - '#050306'
    - '#756b69'
    - '#999999'
  brandStrength: 0.3926309049129486
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
