name: weird.agency
favicon: null
layout_spectrum: 0.75836
typography_spectrum: 0.37153
title: Welcome to Weird.Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7f4e6d'
    - '#fff0d4'
    - '#a97087'
    - '#e2b5ae'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
