typography_spectrum: 0
color:
  brandColors:
    - '#000000'
    - '#005595'
    - '#611100'
    - '#9299ae'
    - '#3d95af'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.8125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29032
analytics:
  google: null
  facebook: null
  twitter: null
name: weird.agency
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Weird.Agency
purpose: []
